
name: Node.js CI/CD pipeline

# Trigger the workflow based on the push and pull events to the main branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use Node.js version 22

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Docker image
      - name: Build Docker Image
        run: docker build -t node-docker-app .

      # Step 5: Login to Docker
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Step 6: Push to Docker hub
      - name: Push Image to Docker hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node-docker-app